---
title: "ST 558 Final Project Modeling"
format: html
editor: visual
---

# Modeling

## Introduction

## Load the Data

```{r}
# Load in libraries
library(tidyverse)
library(tidymodels)
```

```{r}
# Load in Diabetes Health Indicators Dataset
diabetes_data <- read_csv("API_Docker/diabetes_binary_health_indicators_BRFSS2015.csv",
                          show_col_types = FALSE)

# Select only the variables used for my analysis and convert binary to factor
analysis_variables <- c("Diabetes_binary", "HighBP", "Smoker", "PhysActivity",
                        "Fruits", "Veggies", "HvyAlcoholConsump", "GenHlth",
                        "DiffWalk", "Sex", "Age", "Income")
diabetes_data <- diabetes_data |>
  select(all_of(analysis_variables)) |>
  mutate(Diabetes_binary = factor(Diabetes_binary),
         HighBP = factor(HighBP),
         Smoker = factor(Smoker),
         PhysActivity = factor(PhysActivity),
         Fruits = factor(Fruits), 
         Veggies = factor(Veggies),
         HvyAlcoholConsump = factor(HvyAlcoholConsump),
         DiffWalk = factor(DiffWalk),
         Sex = factor(Sex))

diabetes_data
```

## Split the Data

```{r}
# Set seed for reproducibility
set.seed(123)

# Get training split with 70% of the data, and test split with 30%
# Stratified on the response variable Diabetes_binary
diabetes_split <- initial_split(diabetes_data, prop = 0.7, 
                                strata = Diabetes_binary)
diabetes_train <- training(diabetes_split)
diabetes_test <- testing(diabetes_split)

# Create 5 fold Cross Validation splits
diabetes_folds <- vfold_cv(diabetes_train, v = 5)
```

## Create Models

### Classification Tree

```{r}
diabetes_tree_rec <- recipe(Diabetes_binary ~ ., data = diabetes_data) |>
  step_normalize(all_numeric())
```

```{r}
diabetes_tree_mod <- decision_tree(tree_depth = 30,
                          min_n = 20,
                          cost_complexity = tune()) |>
  set_engine("rpart") |>
  set_mode("classification")
```

```{r}
diabetes_tree_wkf <- workflow() |>
  add_recipe(diabetes_tree_rec) |>
  add_model(diabetes_tree_mod)
```

```{r}
diabetes_tree_grid <- grid_regular(cost_complexity(),
                                   levels = 10)
diabetes_tree_fits <- diabetes_tree_wkf |>
  tune_grid(resamples = diabetes_folds,
            grid = diabetes_tree_grid,
            metrics = metric_set(mn_log_loss))

diabetes_tree_fits |>
  collect_metrics() |>
  filter(.metric == "mn_log_loss") |>
  arrange(mean)
```

```{r}
diabetes_tree_best_params <- select_best(diabetes_tree_fits, 
                                         metric = "mn_log_loss")

diabetes_tree_best_params
```

```{r}
diabetes_tree_final_wkf <- diabetes_tree_wkf |>
  finalize_workflow(diabetes_tree_best_params)

diabetes_tree_final_fit <- diabetes_tree_final_wkf |>
  last_fit(diabetes_split, metrics = metric_set(mn_log_loss))

diabetes_tree_final_fit |>
  collect_metrics()
```

### Random Forest

```{r}
diabetes_rf_rec <- recipe(Diabetes_binary ~ HighBP + Smoker + PhysActivity + 
                            Fruits + Veggies + HvyAlcoholConsump + 
                            GenHlth + DiffWalk + Sex + Age + Income, 
                          data = diabetes_data) |>
  step_normalize(all_numeric())
```

```{r}
diabetes_rf_mod <- rand_forest(mtry = tune(),
                               trees = 150) |>
  set_engine("ranger", importance = "impurity") |>
  set_mode("classification")
```

```{r}
diabetes_rf_wkf <- workflow() |>
  add_recipe(diabetes_rf_rec) |>
  add_model(diabetes_rf_mod)
```

```{r}
diabetes_rf_grid <- grid_regular(mtry(range = c(1, 11)),
                                 levels = 5)

diabetes_rf_fit <- diabetes_rf_wkf |>
  tune_grid(resamples = diabetes_folds,
            grid = diabetes_rf_grid,
            metrics = metric_set(mn_log_loss))

diabetes_rf_fit |>
  collect_metrics() |>
  filter(.metric == "mn_log_loss") |>
  arrange(mean)
```

```{r}
diabetes_rf_best_params <- select_best(diabetes_rf_fit, metric = "mn_log_loss") 

diabetes_rf_final_wkf <- diabetes_rf_wkf |>
  finalize_workflow(diabetes_rf_best_params) 

diabetes_rf_final_fit <- diabetes_rf_final_wkf |>
  last_fit(diabetes_split, metrics = metric_set(mn_log_loss))

diabetes_rf_final_fit |>
  collect_metrics()
```

### Final Model Selection

```{r}
rbind(
  diabetes_tree_final_fit |>
    collect_metrics() |>
    mutate(Model = "Tree", .before = ".metric"),
  diabetes_rf_final_fit |>
    collect_metrics() |>
    mutate(Model = "RF", .before = ".metric")
)
```

Fit the best model on the full data set.

```{r}
diabetes_best_model <- diabetes_rf_final_wkf |>
  fit(diabetes_data)

diabetes_best_model
```

```{r}
diabetes_rf_final_model <- extract_fit_engine(diabetes_best_model)

diabetes_rf_final_model$variable.importance |>
  enframe(name = "Variable", value = "Importance") |>
  arrange(Importance) |>
  mutate(Variable = factor(Variable, levels = Variable)) |>
  ggplot(aes(x = Importance, y = Variable)) +
  geom_bar(stat = "identity")
```
